name: episode_1
description: A new Flutter project.

dependencies:
  url_launcher: any
  font_awesome_flutter: any
  
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  rxdart: ^0.23.1  
  flutter:
    sdk: flutter

  cupertino_icons: any

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart
      fonts: 
        - asset: fonts/PressStart2p-Regular.ttf

