name: episode_1
description: A new Flutter project.

dependencies:
  url_launcher: any
  
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2  
  flutter:
    sdk: flutter

  cupertino_icons: any

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

